### ISSUE TITLE
Blank background on image from chromecast-images

### ISSUE THREAD

**Issue by manosnoam** [ifl0w/RandomWallpaperGnome3#36]
Setting up chromecast-images according to your instructions:
https://github.com/ifl0w/RandomWallpaperGnome3/wiki/Generic-JSON-Source#chromecast-images

Works great but got a black background when fetching this image:

https://lh3.googleusercontent.com/-skB9ljKV58M/UXp3kiaG3DI/AAAAAAAAgRM/hZ3rTbu1XwU/s1920-w1920-h1080-c/The%2BDream%2BCatcher%2B-%2BPalouse%252CWA.jpg

Note 1: I can see the tiny image in the panel UI to choose from history, but choosing it make the desktop background blanked in total black.

Note 2: Changing screen resollution has no effect - background is still black with this spesific image url.

Note 3: Downloading this image, and setting it as Desktop background from Linux Settings (or from Firefox - "Set as desktop background") - work OK.

**Comment by ifl0w** [comment]
Well, this is quite interesting ... 
I could reproduce this bug with the following settings:
`Request URL: https://raw.githubusercontent.com/dconnolly/chromecast-backgrounds/master/backgrounds.json`
`JSON Path: $[386].url`

386 is the current index of the "faulty" picture. This index might change in the future if the list of chrome cast images is updated.

I did not fully understand the cause of the bug since I had not much time to investigate. 
But my best bet is that there is something odd with the name of the picture in the URL. The names get URL decoded and the pictures are then stored under the decoded name. The decoded name of the broken picture is still somewhat URL encoded. 
`The%2BDream%2BCatcher%2B-%2BPalouse%252CWA.jpg` translates to `The+Dream+Catcher+-+Palouse%2CWA.jpg` which translates again to `The+Dream+Catcher+-+Palouse,WA.jpg`.

This might be the problem here since I only decode ones but I am not 100% sure and I'll investigate this further when I have more time. For now, this is not a very critical bug since it only affects a minority of pictures. It is more of an annoyance. 

Thank You for reporting! :)

**Comment by manosnoam** [comment]
Hi, 
It happened again, now with this image source:
https://lh5.googleusercontent.com/-5vOp8Qd9Cr0/UZURZbC6EvI/AAAAAAAAgTY/jZBHwF9W4VU/s1920-w1920-h1080-c/In%2Ba%2BForeign%2BLand%2B-%2BWest%2BFjords%252C%2BIceland.jpg

Do you find similar cause ?

**Comment by ifl0w** [comment]
This should now be fixed and will be included in the next update.

**Comment by DBY047** [comment]
@ifl0w it is not fixed. I switch from Bing Picture of the day to Chromecast Images and I get the same bad image.

![Image](https://github.com/user-attachments/assets/59ddfe03-d2a7-406d-8789-083a92093a45)

**Comment by ifl0w** [comment]
@DBY047 do you have some more information on which image was downloaded. I guess this is a separate issue to the one fixed here. If this problem persists, then please open a separate issue with further information.
